insert into users (username, name, password, user_role, email) values ('steve', 'Steve', 'iAmTheBoss', 'boss', 'steve.morse@nokia.com');
insert into users (username, name, user_role, email) values ('matt', 'Matt', 'employee', 'matthew.ng@nokia.com');
insert into users (username, name, user_role, email) values ('ukeme', 'Ukeme', 'employee', 'ukeme.bassey@nokia.com');
insert into users (username, name, user_role, email) values ('saad', 'Saad', 'employee', 'mohammad.s.khan@nokia.com');
insert into users (username, name, user_role, email) values ('jaspreet', 'Jaspreet', 'employee', 'jaspreet.thind@nokia.com');
insert into users (username, name, user_role, email) values ('shahram', 'Shahram', 'employee', 'shahram.haghighi@nokia.com');
insert into users (username, name, user_role, email) values ('allanC', 'Allan C', 'employee', 'allan.c.cybulskie@nokia.com');
insert into users (username, name, user_role, email) values ('alanI', 'Alan I', 'employee', 'alan.ibrahim@nokia.com');
insert into users (username, name, user_role, email) values ('ahmad', 'Ahmad', 'employee', 'ahmad.moghrabi@nokia.com');
insert into users (username, name, user_role, email) values ('fan', 'Fan', 'employee', 'fan.mo@nokia.com');
insert into users (username, name, user_role, email) values ('tao', 'Tao', 'employee', 'tao.zhu@nokia.com');
insert into users (username, name, user_role, email) values ('paul', 'Paul', 'employee', 'paul.1.ma@nokia.com');
insert into users (username, name, user_role, email) values ('gloria', 'Gloria', 'employee', 'ruoying.gong@nokia.com');
insert into users (username, name, user_role, email) values ('chris', 'Chris', 'employee', 'christopher.mcintosh@nokia.com');
insert into users (username, name, user_role, email) values ('rohit', 'Rohit', 'employee', 'rohit.jain@nokia.com');
insert into users (username, name, user_role, email) values ('kevin', 'Kevin', 'employee', 'kevin.chow@nokia.com');
insert into users (username, name, user_role, email) values ('mayuran', 'Mayuran', 'employee', 'mayuran.kanesananthakuru@nokia.com@nokia.com');
insert into users (username, name, user_role, email) values ('maryam', 'Maryam', 'employee', 'maryam.ahmadi@nokia.com');
insert into users (username, name, user_role, email) values ('ashique', 'Ashique', 'employee', 'ashique.ornab@nokia.com');
insert into users (username, name, user_role, email) values ('chizhang', 'Chi Zhang', 'employee', 'chi.zhang@nokia.com');
insert into users (username, name, user_role, email) values ('payam', 'Payam', 'employee', 'payam.belkameh@nokia.com');
insert into users (username, name, user_role, email) values ('ken', 'Ken', 'employee', 'ken.brunet@nokia.com');
insert into users (username, name, user_role, email) values ('gururaj', 'Gururaj', 'employee', 'gururaj.byrappa@nokia.com');
insert into users (username, name, user_role, email) values ('jun', 'Jun', 'employee', 'jun.feng@nokia.com');
insert into users (username, name, user_role, email) values ('jeff', 'Jeff', 'employee', 'jeffrey.furry@nokia.com');
insert into users (username, name, user_role, email) values ('ambili', 'Ambili', 'employee', 'ambili.muraleedharan@nokia.com');
insert into users (username, name, user_role, email) values ('abhijit', 'Abhijit', 'employee', 'abhijit.pare@nokia.com');
insert into users (username, name, user_role, email) values ('chipham', 'Chi Pham', 'employee', 'chi.pham@nokia.com');
insert into users (username, name, user_role, email) values ('phanh', 'Phanh', 'employee', 'phanh.pham@nokia.com');
insert into users (username, name, user_role, email) values ('riyas', 'Riyas', 'employee', 'riyas.valiyapalathingal@nokia.com');

