insert into users (username, name, password, user_role) values ('steve', 'Steve', 'iAmTheBoss', 'boss');
insert into users (username, name, user_role) values ('matt', 'Matt', 'employee');
insert into users (username, name, user_role) values ('ukeme', 'Ukeme', 'employee');
insert into users (username, name, user_role) values ('saad', 'Saad', 'employee');
insert into users (username, name, user_role) values ('jaspreet', 'Jaspreet', 'employee');
insert into users (username, name, user_role) values ('shahram', 'Shahram', 'employee');
insert into users (username, name, user_role) values ('allanC', 'Allan C', 'employee');
insert into users (username, name, user_role) values ('alanI', 'Alan I', 'employee');
insert into users (username, name, user_role) values ('ahmad', 'Ahmad', 'employee');
insert into users (username, name, user_role) values ('fan', 'Fan', 'employee');
insert into users (username, name, user_role) values ('tao', 'Tao', 'employee');
insert into users (username, name, user_role) values ('paul', 'Paul', 'employee');
insert into users (username, name, user_role) values ('gloria', 'Gloria', 'employee');
insert into users (username, name, user_role) values ('chris', 'Chris', 'employee');
insert into users (username, name, user_role) values ('rohit', 'Rohit', 'employee');
insert into users (username, name, user_role) values ('kevin', 'Kevin', 'employee');
insert into users (username, name, user_role) values ('mayuran', 'Mayuran', 'employee');
insert into users (username, name, user_role) values ('maryam', 'Maryam', 'employee');
